MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
before_validation :ensure_session_token
validates :email, :session_token, presence: true, uniqueness: true
validates :password_digest, presence: true
validates :password, length: { minimum: 6 }, allow_nil: true

attr_reader :password

#FIGVAPER

def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
end

def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    if user && user.is_password?(password)
        user
    else
        nil
    end

end


def is_password?(password)
    pass = BCrypt::Password.new(self.password_digest)
    pass.is_password?(password)
end


def generate_session_token
    SecureRandom::urlsafe_base64
end

def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
end

private

def ensure_session_token
    self.session_token ||= generate_session_token
end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :logged_in?
#CHRRLLL

def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
end


def logged_in?
    !!current_user
end

def login!(user)
    session[:session_token] = user.reset_session_token!
end


def logout!
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
    @current_user = nil
end

def require_logged_in
    redirect_to new_session_url unless logged_in?
end


def require_logged_out
    redirect_to user_url(current_user.id) if logged_in?
end


end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]
    before_action :require_logged_out, only: [:new, :create]

def create
    email = params[:user][:email]
    password = params[:user][:password]
    @user = User.find_by_credentials(email, password)

    if @user
        login!(@user)
        redirect_to user_url(@user.id)
    else
        flash.now[:errors] = ["Invalid credentials"]
        render :new
    end
end


def new
    render :new
end


def destroy
    
    if logged_in?
        logout!
    end

    flash[:messages] = ["You have successfully logged out!"]
    redirect_to new_session_url
    end


end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
    render :new
end


def create
    @user = User.new(user_params)

    if @user.save
        login!(@user)
        redirect_to user_url(@user.id)
    else
        flash.now[:errors] = @user.errors.full_messages
        render :new
    end

end


def show
    @user = User.find(params[:id])
    render :show  
end


private

def user_params
    params.require(:user).permit(:email, :password)
end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "stylesheet" %>
  </head>

<h1>Music App</h1>
<p>
  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

  <% if flash[:messages] %>
      <% flash[:messages].each do |message| %>
      <%= message %>
      <% end %>
  <% end %>
  </p>

  <% if logged_in? %>
  <p>Hello <%= current_user.email %></p>    
  <form action="<%=session_url%>" method="POST">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Logout">
  </form>
  <% else %>
    <a href="<%= new_user_url%>"> Sign Up</a>
    <a href="<%=new_session_url%>"> Log In</a>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<h2>Sign Up!</h2>

<form action= "<%= users_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


<label> Email:
    <input type="text" name="user[email]">
</label>

<br>

<label> Password:
    <input type="password" name="user[password]">
</label>

<br>

<input class= "button" type="submit" value="Sign up">

</form>

MusicApp/app/views/users/show.html.erb
<h1>Welcome, <%= @user.email %>! </h1>